### ISSUE TITLE
Action failing with latest `golang:alpine` image

### ISSUE THREAD

**Issue by caitlinelfring** [andrewslotin/go-proxy-pull-action#5]
I discovered this failing in the latest `golang:alpine` image that's used in this action - [example](https://github.com/get-woke/woke/runs/5611605439?check_suite_focus=true). I haven't run this action in a while, but `golang:alpine` is now go 1.18. Testing this action locally with `golang:1.17-alpine` works as expected.

```
go: go.mod file not found in current directory or any parent directory.
	'go get' is no longer supported outside a module.
	To build and install a command, use 'go install' with a version,
	like 'go install example.com/cmd@latest'
	For more information, see https://golang.org/doc/go-get-install-deprecation
	or run 'go help get' or 'go help install'.
```

From the changelog of 1.18 - https://tip.golang.org/doc/go1.18#go-get
> go get no longer builds or installs packages in module-aware mode. go get is now dedicated to adjusting dependencies in go.mod. Effectively, the -d flag is always enabled. To install the latest version of an executable outside the context of the current module, use [go install example.com/cmd@latest](https://golang.org/ref/mod#go-install). Any [version query](https://golang.org/ref/mod#version-queries) may be used instead of latest. This form of go install was added in Go 1.16, so projects supporting older versions may need to provide install instructions for both go install and go get. go get now reports an error when used outside a module, since there is no go.mod file to update. In GOPATH mode (with GO111MODULE=off), go get still builds and installs packages, as before.

`go get` is still the recommended way to update a package https://pkg.go.dev/about#adding-a-package

Wondering if you might have a recommendation for how to move forward. My workaround is to run the commands in this action myself so I can force go 1.17.

Thanks for your help!

**Comment by andrewslotin** [comment]
Hey @caitlinelfring, good catch and a very informative description. Indeed, `go get` seems to have stopped operating outside of module context starting from `go1.18`. I'm going to release a new version of this action to address this issue.

**Comment by andrewslotin** [comment]
Please give [`v1.0.3`](https://github.com/andrewslotin/go-proxy-pull-action/releases/tag/v1.0.3) a try and let me know if this resolves your issue.
